#!/usr/bin/python3
"""A python file that contains the class definition of a State
and an instance Base = declarative_base()"""

from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class State(Base):
    """An object representation of the table States in our database"""
    __tablename__ = "states"

    """Primary key makes the attribute unique, non null and autogenerated"""
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
