#!/usr/bin/python3
"""A python file that contains the class definition of a State
with an attribute cities related to cities"""

from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class State(Base):
    """An object representation of the table States in our database"""
    __tablename__ = "states"

    """Primary key makes the attribute unique, non null and autogenerated"""
    id = Column(Integer, primary_key=True)
    name = Column(String(128), nullable=False)
    cities = relationship("City", back_populates="state",
                          cascade="all, delete")
